sudo: required
dist: trusty
services:
  - docker

language: go

go:
  - '1.8'

os:
  - linux

env:
  matrix:
    - TARGETS="lint"
    - TARGETS="test"

  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"

install:
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/Masterminds/glide

script:
  - make $TARGETS

after_success:
  # Copy full.cov to coverage.txt because codecov.io requires this file
  - test -f ./build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f ./build/coverage/full.cov
